### ISSUE TITLE
Error starting up or running on M2 Ultra when GPU is at 100%

### ISSUE THREAD

**Issue by Zanshinmu** [graelo/pumas#21] opened 2024-04-12 20:34 UTC
I have an M2 Ultra which usually has one or another job going on it that keeps the GPU at 100%.  

It displays, "Starting up... plist parsing error: `Serve("Invalid value: integer `93642`, expected u16") which also happens if the GPU spikes to 100% after pumas starts.  It will run fine until the GPU spikes to 100%. 

I would really like to replace asitop with pumas on all my machines so hopefully this is fixable.  

<img width="1052" alt="Screenshot 2024-04-12 at 1 25 23 PM" src="https://github.com/graelo/pumas/assets/247462/1003b7ae-d58c-4688-a5f6-10223553df9c">

**Comment by graelo** [comment] 2024-04-12 22:34
Hi, thanks for the report. I'd say it's probably due to a formatting issue in the plist from powermetrics. Could you send here as an attachment the output of the following command?

```
sudo powermetrics --sample-rate 1000 --sample-count 1 --samplers cpu_power,gpu_power,thermal -f plist > output.plist
```

**Comment by Zanshinmu** [comment] 2024-04-12 22:45
On Apr 12, 2024 at 3:34:32 PM, graelo ***@***.***> wrote:

> sudo powermetrics --sample-rate 1000 --sample-count 1 --samplers
> cpu_power,gpu_power,thermal -f plist > output.plist


Attached, thanks for taking a look at this.

-D

**Comment by Zanshinmu** [comment] 2024-04-12 22:48
[output.plist.txt](https://github.com/graelo/pumas/files/14964272/output.plist.txt)

Weird,I couldn't attach until I changed the extension to .txt.   Hope this helps and thanks for taking a look at this.

**Comment by graelo** [comment] 2024-04-12 22:57
Cool, I added your file as part of the tests, and I can immediately reproduce your issue. I'll look into it within the next day and get back to you. Cheers!

**Comment by graelo** [comment] 2024-04-12 23:29
Sorry, the issue was closed automatically when I merged the PR, I did not want that. I'll let you some time to test the next release.

**Closed** 2024-04-12 23:52 UTC

**Comment by Zanshinmu** [comment] 2024-04-13 01:13
Can’t remember if this reopens, but it worked perfectly.  I remember asitop
had a similar issue except with cpu.

Homebrew was pretty fast with the package, had rust installed and was
trying to figure out where the binary built when Homebrew  updated the
package.

Who says open source can’t be responsive?

Thanks again,


-D

**Comment by graelo** [comment] 2024-04-13 06:13
Just FYI, my project is not popular enough to be published on Homebrew (see [rules](https://docs.brew.sh/Acceptable-Formulae#niche-or-self-submitted-stuff)), so I take care of updating the formula in my [graelo/homebrew-tap](https://github.com/graelo/homebrew-tap/blob/main/Formula/pumas.rb). But otherwise, yes, when a formula is published on official Homebrew, their [livecheck](https://docs.brew.sh/Brew-Livecheck#creating-a-check) feature allows them to auto bump the formula.
